### ISSUE TITLE
Compilation errors in Mac OS X, most likely clang related

### ISSUE THREAD

**Issue by christoff-buerger** [2bt/terminal-tracker#1]
The project does not build out of the box in _OS X El Capitan_. The errors while executing make are:

```
g++ -Wall --std=c++11 -I PEGTL/ -O2 src/channel.cpp -c -o obj/channel.o
In file included from src/channel.cpp:1:
In file included from src/channel.h:4:
In file included from src/param.h:6:
src/tune.h:33:29: error: type 'float' cannot be narrowed to 'size_type' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
        Envelope(float v) : nodes({v}), loop(-1) {}
                                   ^
src/tune.h:33:29: note: insert an explicit cast to silence this issue
        Envelope(float v) : nodes({v}), loop(-1) {}
                                   ^
                                   static_cast<size_type>( )
src/channel.cpp:194:9: error: use of undeclared identifier 'rand'
                amp = rand() / float(RAND_MAX) * 2 - 1;
                      ^
src/channel.cpp:194:24: error: use of undeclared identifier 'RAND_MAX'
                amp = rand() / float(RAND_MAX) * 2 - 1;
                                     ^
In file included from src/channel.cpp:1:
In file included from src/channel.h:4:
In file included from src/param.h:3:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:477:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1673:31: error: no matching constructor for initialization of 'Envelope::Node'
            ::new((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1600:18: note: in instantiation of function template specialization
      'std::__1::allocator<Envelope::Node>::construct<Envelope::Node>' requested here
            {__a.construct(__p, _VSTD::forward<_Args>(__args)...);}
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1453:14: note: in instantiation of function template specialization
      'std::__1::allocator_traits<std::__1::allocator<Envelope::Node> >::__construct<Envelope::Node>' requested here
            {__construct(__has_construct<allocator_type, _Tp*, _Args...>(),
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:988:25: note: in instantiation of function template specialization
      'std::__1::allocator_traits<std::__1::allocator<Envelope::Node> >::construct<Envelope::Node>' requested here
        __alloc_traits::construct(__a, _VSTD::__to_raw_pointer(this->__end_));
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:1079:9: note: in instantiation of member function 'std::__1::vector<Envelope::Node,
      std::__1::allocator<Envelope::Node> >::__construct_at_end' requested here
        __construct_at_end(__n);
        ^
src/tune.h:33:22: note: in instantiation of member function 'std::__1::vector<Envelope::Node, std::__1::allocator<Envelope::Node> >::vector' requested here
        Envelope(float v) : nodes({v}), loop(-1) {}
                            ^
src/tune.h:28:3: note: candidate constructor not viable: requires single argument 'v', but no arguments were provided
                Node(float v) : value(v), delta(false) {}
                ^
src/tune.h:24:9: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
        struct Node {
               ^
src/tune.h:24:9: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 0 were provided
src/tune.h:27:3: note: candidate constructor not viable: requires 2 arguments, but 0 were provided
                Node(float v, bool d) : value(v), delta(d) {}
                ^
4 errors generated.
make: *** [obj/channel.o] Error 1
```

Note, that _gcc_ is symlinked to _clang_ in _OS X_. I do not know about _g++_; it seems to be a binary in `/usr/bin`. If I change `g++` in the makefile to `gcc`/`clang` exactly the same errors are thrown.

Maybe the problem has to do with the _Xcode_ command line tools?

**Comment by 2bt** [comment]
Uh, I never tried building with clang. I will look into this...

**Comment by 2bt** [comment]
Another compiler incompatibility. Should be fixed now.

**Comment by christoff-buerger** [comment]
After your fixes only two errors remain:

```
clang++ -Wall --std=c++11 -I PEGTL/ -O2 src/channel.cpp -c -o obj/channel.o
src/channel.cpp:194:9: error: use of undeclared identifier 'rand'
                amp = rand() / float(RAND_MAX) * 2 - 1;
                      ^
src/channel.cpp:194:24: error: use of undeclared identifier 'RAND_MAX'
                amp = rand() / float(RAND_MAX) * 2 - 1;
                                     ^
2 errors generated.
make: *** [obj/channel.o] Error 1
```

I checked the `channel.h`. It seems the standard library providing the `rand` function is not included. Adding `#include <stdlib.h>` in `channel.h`, or better `channel.cpp`, fixes the problem, but then another error pops up:

```
clang++ -Wall --std=c++11 -I PEGTL/ -O2 src/main.cpp -c -o obj/main.o
src/main.cpp:4:10: fatal error: 'sys/inotify.h' file not found
#include <sys/inotify.h>
         ^
1 error generated.
make: *** [obj/main.o] Error 1
```

**Comment by christoff-buerger** [comment]
Side note: unfortunately one cannot reopen an issue in _GitHub_ if not a contributor. Its possible to close the issues one submitted. Reopening is only possible if closed by yourself :(

The issue is still open on _OS X_.

**Comment by 2bt** [comment]
I use `inotify` to track external file changes on instrument definitions but I didn't consider that `inotify` is for linux only. Switching to something less platform specific like `libuv` would be ideal. In the meantime you could just delete every line or block containing 'notify' from `main.cpp` and forego automatic file reload.

**Comment by christoff-buerger** [comment]
Maybe you can use [_fswatch_](https://github.com/emcrisostomo/fswatch). It is supported by _Homebrew_ and therefore easy to install in _OS X_.

_libuv_ is also supported by _Homebrew_. It looks more professional, but also much bigger with much more use cases in mind.

**Comment by christoff-buerger** [comment]
Further missing libraries pop up, but all can be installed via _Homebrew_:
- `libsndfile`
- `portmidi`

**Comment by christoff-buerger** [comment]
After uncommenting all notify stuff, i.e.:

```
<SNAP>

int inotify_fd = 0;
int tunewatch = 0;

if (tunewatchfile) {
    if (!load_tune(tune, tunewatchfile)) {
        if (write_tune) {
            printf("Error loading tune watch file\n");
            return 1;
        }
        msg_win.say("Error loading tune watch file");
    }
    inotify_fd = inotify_init1(IN_NONBLOCK);
    tunewatch = inotify_add_watch(inotify_fd, tunewatchfile, IN_MODIFY);
}

<SNAP>

if (tunewatchfile) {
    inotify_event event;
    int r;
    while ((r = read(inotify_fd, &event, sizeof(inotify_event))) > 0) {
        if (event.wd != tunewatch) continue;

        msg_win.say("Reloading tune watch file... ");

        inotify_rm_watch(inotify_fd, tunewatch);
        tunewatch = inotify_add_watch(inotify_fd, tunewatchfile, IN_MODIFY);

        if (!load_tune(tune, tunewatchfile)) msg_win.append("error.");
        else msg_win.append("done.");
    }
}

<SNAP>
```

more compile errors pop up:

```
clang++ -Wall --std=c++11 -I PEGTL/ -O2 src/channel.cpp -c -o obj/channel.o
clang++ -Wall --std=c++11 -I PEGTL/ -O2 src/fx.cpp -c -o obj/fx.o
clang++ -Wall --std=c++11 -I PEGTL/ -O2 src/main.cpp -c -o obj/main.o
src/main.cpp:75:2: error: use of undeclared identifier 'atexit'; did you mean '_exit'?
        atexit(&done);
        ^~~~~~
        _exit
/usr/include/unistd.h:429:7: note: '_exit' declared here
void     _exit(int) __dead2;
         ^
src/main.cpp:75:9: error: cannot initialize a parameter of type 'int' with an rvalue of type 'void (*)()'
        atexit(&done);
               ^~~~~
/usr/include/unistd.h:429:16: note: passing argument to parameter here
void     _exit(int) __dead2;
                  ^
2 errors generated.
make: *** [obj/main.o] Error 1
```

All can be fixed by adding `#include <stdlib.h>` to `main.cpp`.

**Comment by 2bt** [comment]
Thanks a lot for the feedback! :+1:

**Comment by christoff-buerger** [comment]
Next error is:

```
src/server.cpp:1:10: fatal error: 'SDL/SDL.h' file not found
#include <SDL/SDL.h>
```

Are you using [_libsdl_](https://www.libsdl.org)? _Homebrew_ provides several versions of this library: `sdl` and `sdl2`, versions 1.2.15 and 2.0.4 respectively. Which one to use?

**Comment by 2bt** [comment]
Just `libSDL`, the older version.

**Comment by christoff-buerger** [comment]
Installed further libraries via _Homebrew_:
- `sdl`
- `pegtl`

Now everything compiles and IT WORKS!
